'use strict';
const DATA=window.CHARACTERS||[];
const ART=window.POKEMON_ART||{};
const STATUSES=['planned','in-progress','edited','tested'];
const STATUS_LABEL={'planned':'Planned','in-progress':'In progress','edited':'Edited','tested':'Tested'};
const PROFILE_FIELDS=['newName','personality','relationship','role','appearance','notes'];
const PROFILE_LABELS={newName:'Name',personality:'Personality & voice',relationship:'Relationships',role:'Story role / era',appearance:'Appearance',notes:'Character notes'};
const SCENE_FIELDS=['title','location','phase','summary','trigger','tags','dialogue','gifts','notes','where','testing','status'];
const PUBLIC_SCENE_FIELDS=['title','location','phase','summary','trigger','tags','dialogue','gifts','notes'];
const SCENE_LABELS={title:'Appearance title',location:'Location',phase:'Main story / postgame',summary:'What happens',trigger:'Trigger',tags:'Appearance markers',dialogue:'Dialogue',gifts:'Gifts / items / progression',notes:'Documented notes'};
const CHANGE_FIELDS=['title','category','original','planned','actual','where','testing','romVersion','date','status'];
const KEY='luce-platinum-character-notebook-v1';
const MODES=['official','luce','drafts'];
const MODE_NAMES={official:'Official',luce:"Luce’s Version",drafts:'Drafts'};
const EMPTY_SNAPSHOT=()=>({schema:1,kind:'luce-confirmed',updatedAt:null,characters:{}});
let notebook={schema:2,updatedAt:null,project:{romVersion:'',notes:''},characters:{},confirmed:EMPTY_SNAPSHOT(),history:[]};
let published=EMPTY_SNAPSHOT(),snapshotError='',mode='official',activeTab='overview',draftReturnTab=null;
let db=null,pendingImport=null,saveChain=Promise.resolve();
const $=id=>document.getElementById(id);
const copy=value=>JSON.parse(JSON.stringify(value));
const str=(v,max=30000)=>typeof v==='string'?v.slice(0,max):'';
const iso=v=>typeof v==='string'&&!Number.isNaN(Date.parse(v))?new Date(v).toISOString():null;
const isImage=v=>typeof v==='string'&&/^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(v)&&v.length<=12*1024*1024;
function record(c){
 if(!notebook.characters[c.id])notebook.characters[c.id]={profile:{newName:c.id==='mum'?'Louisa':c.id==='player'?'Luce':'',personality:'',relationship:'',role:'',appearance:'',notes:c.id==='player'?'Starter plan: Turtwig → Andi; Chimchar → Rory; Piplup → Percy.':''},image:'',changes:defaultChanges(c),encounters:{},linked:{}};
 return notebook.characters[c.id];
}
function sceneRecord(c,e){const r=record(c);if(!r.encounters[e.id])r.encounters[e.id]={status:'planned',teams:{}};const scene=r.encounters[e.id];for(const key of SCENE_FIELDS)if(scene[key]===undefined)scene[key]=key==='status'?'planned':'';scene.teams||={};return scene;}
function cleanParty(values){return arr(values).slice(0,6).map(p=>({species:str(p.species,200),level:p.level==null||p.level===''?'':Number.isFinite(Number(p.level))?Math.min(100,Math.max(1,Number(p.level))):'',ability:str(p.ability,200),item:str(p.item,200),moves:arr(p.moves).slice(0,4).map(v=>str(v,200))}));}
function snapshotSlot(snapshot,cid,scope,eid,key,create=false){
 let c=snapshot.characters[cid];if(!c&&create)c=snapshot.characters[cid]={profile:{},encounters:{}};if(!c)return null;
 if(scope==='profile'){if(create)c.profile||={};return [c.profile||{},key];}
 if(scope==='image')return [c,'image'];
 let e=c.encounters?.[eid];if(!e&&create){c.encounters||={};e=c.encounters[eid]={fields:{},teams:{}};}if(!e)return null;
 if(scope==='scene'){if(create)e.fields||={};return [e.fields||{},key];}
 if(scope==='team'){if(create)e.teams||={};return [e.teams||{},String(key)];}
 return null;
}
function entryIn(snapshot,cid,scope,eid,key){const slot=snapshotSlot(snapshot,cid,scope,eid,key);return slot?.[0][slot[1]]||null;}
function allEntries(snapshot){const entries=[];for(const c of DATA){const x=snapshot.characters[c.id];if(!x)continue;for(const key of PROFILE_FIELDS)if(x.profile?.[key])entries.push([c.id,'profile','',key,x.profile[key]]);if(x.image)entries.push([c.id,'image','','',x.image]);for(const e of c.encounters){const r=x.encounters?.[e.id];if(!r)continue;for(const key of PUBLIC_SCENE_FIELDS)if(r.fields?.[key])entries.push([c.id,'scene',e.id,key,r.fields[key]]);for(let i=0;i<Math.max(1,e.teams.length);i++)if(r.teams?.[i])entries.push([c.id,'team',e.id,i,r.teams[i]]);}}return entries;}
function mergedSnapshot(){
 const result=copy(published);
 for(const [cid,scope,eid,key,entry] of allEntries(notebook.confirmed)){const prior=entryIn(result,cid,scope,eid,key);if(!prior||entry.confirmedAt>=prior.confirmedAt){const [obj,k]=snapshotSlot(result,cid,scope,eid,key,true);obj[k]=copy(entry);}}
 result.updatedAt=allEntries(result).reduce((v,x)=>x[4].confirmedAt>v?x[4].confirmedAt:v,result.updatedAt||'')||null;
 return result;
}
function confirmedEntry(c,scope,eid='',key=''){const a=entryIn(published,c.id,scope,eid,key),b=entryIn(notebook.confirmed,c.id,scope,eid,key);return !a?b:!b?a:b.confirmedAt>=a.confirmedAt?b:a;}
function confirmedValue(c,scope,eid='',key=''){const entry=confirmedEntry(c,scope,eid,key);return entry&&entry.value!==null?copy(entry.value):null;}
function hasConfirmed(c){return allEntries(mergedSnapshot()).some(x=>x[0]===c.id&&x[4].value!==null);}
function slotLabel(c){return 'Slot '+String(DATA.indexOf(c)+1).padStart(2,'0');}
function displayName(c){return mode==='official'?c.name:mode==='drafts'?record(c).profile.newName||c.name:confirmedValue(c,'profile','','newName')||'';}
function displayRole(c){return mode==='official'?c.role:mode==='drafts'?record(c).profile.role||c.role:confirmedValue(c,'profile','','role')||'';}
function photo(c){if(mode==='official')return c.image?'images/'+c.image:null;if(mode==='drafts')return record(c).image||(c.image?'images/'+c.image:null);return confirmedValue(c,'image');}
function portrait(c,cls=''){const path=photo(c);return path?`<img class="${cls}" src="${esc(path)}" alt="${esc(mode==='official'?(c.imageAlt||c.name+' — original character'):displayName(c)||slotLabel(c))}" loading="lazy">`:'<span class="portrait-empty" aria-hidden="true"></span>';}
function pokemonKey(species){return str(species).replace(/\s*\([^)]*\)\s*/g,'').trim();}
function pokemonImage(species){const key=pokemonKey(species),ref=ART[key];if(ref)return `<img class="pokemon-art" src="${esc(ref.artwork)}" data-art-fallback="${esc(ref.sprite)}" alt="${esc(key)} official artwork" loading="lazy" referrerpolicy="no-referrer">`;const custom=arr(window.POKEMON).find(p=>p.name.toLowerCase()===key.toLowerCase());return custom?`<span class="custom-pokemon-art" style="--sheet:url('${esc('../'+custom.sheet)}')" role="img" aria-label="${esc(key+' custom sprite')}"></span>`:'';}
function pokemonCards(species,label='Pokémon'){const unique=[...new Set(arr(species))];return unique.length?`<h3>${esc(label)}</h3><div class="pokemon-gallery">${unique.map(s=>`<figure>${pokemonImage(s)}<figcaption>${esc(s)}</figcaption></figure>`).join('')}</div>`:'';}
function counts(c){const scenes=c.encounters.filter(e=>!e.dataOnly),battle=e=>arr(e.tags).some(t=>/battle/i.test(t));return {scenes:scenes.filter(e=>!e.repeatable).length,battles:scenes.filter(battle).length,repeat:scenes.filter(e=>e.repeatable).length};}
function progress(c){const list=record(c).changes,done=list.filter(x=>x.status==='tested').length;return {done,total:list.length,percent:list.length?Math.round(done/list.length*100):0,edited:list.filter(x=>['edited','tested'].includes(x.status)).length};}
function updateDate(obj){obj.updatedAt=new Date().toISOString();}
function buildNav(){
 const search=$('search').value.toLowerCase(),group=$('group').value,current=location.hash.slice(1);
 const filtered=DATA.filter(c=>(!group||c.category===group)&&(mode==='luce'?`${displayName(c)} ${displayRole(c)} ${slotLabel(c)}`:`${c.name} ${mode==='drafts'?record(c).profile.newName:''} ${c.role}`).toLowerCase().includes(search));
 const sorted=[...new Set(filtered.map(c=>c.category))].flatMap(g=>filtered.filter(c=>c.category===g));let html='',last='';
 for(const c of sorted){if(last!==c.category){last=c.category;html+=`<p class="nav-group">${mode==='luce'?'Character slots':esc(last)}</p>`;}const name=displayName(c);html+=`<a class="nav-item ${current===c.id?'active':''}" href="#${esc(c.id)}">${portrait(c)}<span>${name?esc(name):`<span class="blank-name">&nbsp;</span>`}${mode==='drafts'&&record(c).profile.newName?`<small>Original: ${esc(c.name)}</small>`:mode==='luce'?`<small>${slotLabel(c)}</small>`:''}</span>${mode==='drafts'?`<i class="nav-dot ${progress(c).percent===100?'complete':''}"></i>`:''}</a>`;}
 $('character-nav').innerHTML=html||'<p class="help">No matching characters.</p>';return filtered;
}
function renderChrome(){
 document.body.dataset.mode=mode;
 const group=$('group').value;const categories=[...new Set(DATA.map(c=>c.category))];$('group').innerHTML='<option value="">All characters</option>'+categories.map((value,i)=>`<option value="${esc(value)}">${mode==='luce'?'Group '+(i+1):esc(value)}</option>`).join('');$('group').value=group;
 $('draft-tools').hidden=mode!=='drafts';$('reference-note').hidden=mode==='drafts';
 $('reference-note').textContent=mode==='official'?'Original Pokémon Platinum reference. Read-only.':'Confirmed values only. Unconfirmed fields remain blank.';
 $('mode-label').textContent=MODE_NAMES[mode];$('index-heading').textContent=mode==='official'?'Official character index':mode==='luce'?"Luce’s character index":'Draft character index';
 $('search').placeholder=mode==='official'?'Search official characters…':mode==='luce'?'Search confirmed names…':'Search names…';
 document.querySelectorAll('[data-mode]').forEach(button=>{const active=button.dataset.mode===mode;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});
}
function dashboard(){
 const filtered=buildNav(),all=DATA.map(progress),allScenes=DATA.reduce((n,c)=>n+counts(c).scenes,0),allBattles=DATA.reduce((n,c)=>n+counts(c).battles,0),entries=allEntries(mergedSnapshot()).filter(x=>x[4].value!==null);
 const heading=mode==='official'?'The Platinum character index.':mode==='luce'?"Luce’s confirmed cast.":'The drafting notebook.';
 const description=mode==='official'?'Original characters, appearances, Pokémon teams and rewards from Pokémon Platinum.':mode==='luce'?'Only explicitly confirmed changes appear here. Everything else stays blank.':'Plan customisations beside the official reference, record ROM edits and confirm finished changes.';
 const metrics=mode==='official'?[[DATA.length,'Character profiles'],[allScenes,'Documented scenes'],[allBattles,'Battle entries'],[Object.keys(ART).length,'Pokémon art references']]:mode==='luce'?[[DATA.length,'Character slots'],[DATA.filter(hasConfirmed).length,'Slots with confirmations'],[entries.length,'Confirmed fields / teams'],[published.updatedAt?published.updatedAt.slice(0,10):'—','Published snapshot']]:[[DATA.length,'Character profiles'],[DATA.filter(c=>record(c).profile.newName).length,'Draft names'],[all.reduce((n,p)=>n+p.edited,0),'Changes edited'],[all.reduce((n,p)=>n+p.done,0),'Changes tested']];
 document.title=MODE_NAMES[mode]+' · Luce Characters';
 $('main').innerHTML=`<div class="hero"><div><span class="eyebrow">${esc(MODE_NAMES[mode].toUpperCase())} / CHARACTER INDEX</span><h1>${heading}</h1><p>${description}</p></div><span class="edition">SINNOH / PLATINUM</span></div><div class="stats">${metrics.map(([v,label])=>`<div class="stat"><b>${esc(v)}</b><span>${esc(label)}</span></div>`).join('')}</div>${mode==='official'?'<div class="notice subtle">A continuous scene is one reference entry. Repeatable visits are listed separately. Counts describe the documented timeline, not every possible conversation.</div>':mode==='luce'&&!entries.length?'<div class="notice subtle">No changes have been confirmed yet. Use Drafts to confirm a field or encounter after updating the ROM.</div>':''}<div class="section-title"><h2>${mode==='luce'?'Character slots':'Choose a character'}</h2><span>${filtered.length} profiles</span></div><div class="cards">${filtered.map(c=>{const n=counts(c),name=displayName(c);return `<a class="character-card" href="#${esc(c.id)}" aria-label="${esc(name||slotLabel(c))}"><div class="card-image"><span class="card-group">${mode==='luce'?slotLabel(c):esc(c.category)}</span>${portrait(c)}</div><div class="card-body"><h3>${name?esc(name):'&nbsp;'}</h3>${mode==='drafts'?`<div class="replacement">Original: ${esc(c.name)}</div>`:''}<p>${esc(displayRole(c))||'&nbsp;'}</p><div class="card-meta">${mode==='luce'?`<span>${slotLabel(c)}</span><span>${hasConfirmed(c)?'Confirmed entries':' '}</span>`:`<span>${n.scenes} scenes · ${n.repeat} repeatable</span>${mode==='drafts'?`<span>${progress(c).done}/${progress(c).total} tested</span>`:''}`}</div>${mode==='drafts'?`<div class="progress"><span style="width:${progress(c).percent}%"></span></div>`:''}</div></a>`;}).join('')}</div>${!filtered.length?'<div class="empty"><h2>No matching characters</h2></div>':''}${mode==='drafts'?`<section class="panel"><h2>Current ROM build</h2><div class="form-grid">${field('Build / backup name',notebook.project.romVersion,'data-project="romVersion"')}${field('Private project notes',notebook.project.notes,'data-project="notes"','textarea')}</div></section>${recentHTML()}${publicationPanel()}${historyPanel()}`:''}`;
 bindCommon();
}
function view(){
 renderChrome();const c=DATA.find(c=>c.id===location.hash.slice(1));buildNav();if(!c){dashboard();return;}
 if(mode!=='drafts'&&activeTab==='changes')activeTab='overview';const n=counts(c),name=displayName(c);
 document.title=(name||slotLabel(c))+' · '+MODE_NAMES[mode];
 const tabs=[['overview',mode==='drafts'?'Profile & customisation':'Profile'],['appearances','Appearances & teams'],...(mode==='drafts'?[['changes','Changes & testing']]:[])];
 $('main').innerHTML=`<div class="breadcrumbs"><a href="#">${esc(MODE_NAMES[mode].toUpperCase())} INDEX</a> / ${mode==='luce'?slotLabel(c):esc(c.category.toUpperCase())}</div><div class="profile-hero"><div class="portrait">${portrait(c)}</div><div><span class="badge">${esc(MODE_NAMES[mode])}</span><h1>${esc(name)||'&nbsp;'}</h1><p>${esc(displayRole(c))||'&nbsp;'}</p>${mode==='drafts'?`<p>Original: <strong>${esc(c.name)}</strong></p>`:''}${mode!=='luce'?`<p><strong>${n.scenes}</strong> documented scenes · <strong>${n.battles}</strong> battle entries · <strong>${n.repeat}</strong> repeatable entries</p>`:`<p class="help">${slotLabel(c)} · unconfirmed details remain blank</p>`}</div></div><div class="tabs" role="tablist" aria-label="Character sections">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${activeTab===id}" id="tab-${id}" aria-controls="tab-content" data-tab="${id}" class="${activeTab===id?'active':''}">${label}</button>`).join('')}</div><div id="tab-content" role="tabpanel" aria-labelledby="tab-${activeTab}">${activeTab==='overview'?overview(c):activeTab==='appearances'?timeline(c):changes(c)}</div>`;
 bindCommon(c);document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{activeTab=button.dataset.tab;draftReturnTab=null;view();$('tab-'+activeTab).focus();});
}
function switchMode(next){
 if(!MODES.includes(next)||next===mode)return;
 const open=[...document.querySelectorAll('.encounter[open]')].map(el=>el.dataset.encounter),filter=$('phase-filter')?.value||'',scroll=window.scrollY;
 if(mode==='drafts'&&activeTab==='changes')draftReturnTab='changes';
 mode=next;if(mode!=='drafts'&&activeTab==='changes')activeTab='overview';else if(mode==='drafts'&&draftReturnTab)activeTab=draftReturnTab;
 try{localStorage.setItem(KEY+'-mode',mode);}catch{}
 view();for(const id of open){const el=document.querySelector(`[data-encounter="${CSS.escape(id)}"]`);if(el)el.open=true;}
 if($('phase-filter')){$('phase-filter').value=filter;filterTimeline();}window.scrollTo({top:scroll,behavior:'instant'});
}
function readonlyField(label,value,entry){return `<div class="read-field"><h3>${esc(label)}</h3><div class="read-value">${value==null||value===''?'&nbsp;':esc(value)}</div>${entry&&entry.value!==null?`<small class="confirmed-meta">Confirmed ${esc(entry.confirmedAt.slice(0,10))}${entry.romVersion?' · '+esc(entry.romVersion):''}</small>`:''}</div>`;}
function officialProfile(c){const species=[...new Set(c.encounters.flatMap(e=>[...e.teams.flatMap(t=>t.pokemon.map(p=>pokemonKey(p.species))),...arr(e.giftPokemon),...arr(e.featuredPokemon)]))];return `<section class="panel"><span class="eyebrow">ORIGINAL PLATINUM REFERENCE</span><h2 style="margin-top:10px">Who they are</h2><p>${esc(c.personality)}</p>${list('Place in the story',c.storyRelevance||c.relevance||c.role)}${list('Relationships',c.relationships)}${list('Progression responsibilities',c.responsibilities)}${gallery(c)}${pokemonCards(species,'Pokémon associated with this character')}<p class="help">Official Pokémon artwork © Nintendo / Game Freak / Creatures. Pokémon artwork and Platinum sprites are hosted by the PokeAPI sprite archive; sources are linked below.</p></section>`;}
function confirmControl(c,scope,key='',eid=''){
 const entry=confirmedEntry(c,scope,eid,key),draft=draftValue(c,scope,eid,key),same=entry?.value!==null&&entry?.value!==undefined&&JSON.stringify(entry.value)===JSON.stringify(draft);
 const attrs=`data-confirm-scope="${scope}" data-confirm-key="${esc(key)}" data-confirm-scene="${esc(eid)}"`;
 return `<div class="confirm-control"><button class="secondary" data-action="confirm-value" ${attrs}>${same?'Confirm again':entry?.value!=null?'Confirm revision':'Confirm for Luce’s Version'}</button>${entry?.value!=null?`<button class="quiet" data-action="unconfirm-value" ${attrs}>Withdraw confirmation</button><small>${same?'Confirmed copy matches this draft':'Draft differs from confirmed copy'} · ${entry.confirmedAt.slice(0,10)}</small>`:'<small>Draft only · not confirmed</small>'}</div>`;
}
function overview(c){
 if(mode==='official')return officialProfile(c)+sources(c);
 if(mode==='luce')return `<section class="panel"><h2>Confirmed character details</h2><div class="confirmed-fields">${PROFILE_FIELDS.map(key=>readonlyField(PROFILE_LABELS[key],confirmedValue(c,'profile','',key),confirmedEntry(c,'profile','',key))).join('')}</div>${confirmedValue(c,'image')?`<img class="custom-image" src="${esc(confirmedValue(c,'image'))}" alt="Confirmed character image">`:''}</section>`;
 const r=record(c);
 return `<div class="two-col"><div>${officialProfile(c)}</div><section class="panel"><span class="eyebrow">DRAFT / PRIVATE UNTIL CONFIRMED</span><h2 style="margin-top:10px">Customise this character</h2><div class="actions"><button class="secondary" data-action="copy-profile">Start from official profile</button></div><div class="draft-fields">${PROFILE_FIELDS.map(key=>`<div>${field(PROFILE_LABELS[key],r.profile[key],`data-profile="${key}"`,key==='newName'?'input':'textarea')}${confirmControl(c,'profile',key)}</div>`).join('')}</div>${r.image?`<img class="custom-image" src="${esc(r.image)}" alt="Draft reference image"><div class="actions"><button class="danger" data-action="remove-image">Remove draft image</button></div>`:''}${r.image||confirmedEntry(c,'image')?.value?confirmControl(c,'image'):''}<label class="upload">Replacement reference image or sprite<input type="file" id="custom-image" accept="image/png,image/jpeg,image/webp,image/gif"></label><p class="help">Images up to 8 MB. Confirmation saves a separate copy. Later draft edits leave the confirmed copy unchanged.</p></section></div><section class="panel"><h2>Linked changes to check</h2><ul class="linked">${arr(c.linkedChanges).map((text,i)=>`<li><label><input type="checkbox" data-linked="${i}" ${r.linked[i]?'checked':''}><span>${esc(text)}</span></label></li>`).join('')}</ul></section>${sources(c)}${publicationPanel()}`;
}
function tagsHTML(tags){return `<div class="event-badges">${arr(tags).map(tag=>`<span class="event-tag tag-${/partner|battle/i.test(tag)?'battle':/gift|item/i.test(tag)?'reward':/repeat/i.test(tag)?'repeat':/progress/i.test(tag)?'progress':'other'}">${esc(tag)}</span>`).join('')}</div>`;}
function timeline(c){return `<div class="notice subtle">${mode==='luce'?'Only confirmed appearance details and team plans are shown. Blank entries retain their relative position in the timeline.':'Coloured markers identify battles, partner battles, gifts, item/HM rewards, progression and repeatable events. Starter variations share the same appearance.'}</div><div class="timeline-toolbar"><span>${c.encounters.length} timeline slots</span><label><span class="sr-only">Filter appearances</span><select id="phase-filter"><option value="">All appearances</option><option value="battle">Battles / partner battles</option><option value="reward">Gifts / items / HMs</option><option value="progress">Progression</option><option value="repeat">Repeatable</option><option value="post">Postgame</option><option value="optional">Optional</option></select></label></div><div id="timeline">${c.encounters.map((e,i)=>sceneHTML(c,e,i)).join('')}</div>${mode!=='luce'?sources(c):''}`;}
function sceneHTML(c,e,i){
 const confirmed=key=>confirmedValue(c,'scene',e.id,key),original=mode!=='luce',title=original?e.title:confirmed('title')||'',locationText=original?e.location:confirmed('location')||'',phase=original?e.phase:confirmed('phase')||'',tags=original?e.tags:arr((confirmed('tags')||'').split(',').map(t=>t.trim()).filter(Boolean));
 const summary=original?e.summary:confirmed('summary')||'';
 const marker=tags.join(' ').toLowerCase();
 return `<details class="encounter ${tags.some(t=>/battle|gift|item/i.test(t))?'key-encounter':''}" data-encounter="${esc(e.id)}" data-marker="${esc(marker)}"><summary><span class="scene-number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(title)||'&nbsp;'}</h3><small>${esc([locationText,phase].filter(Boolean).join(' · '))||'&nbsp;'}</small>${tagsHTML(tags)}</div></summary><div class="encounter-content"><p>${esc(summary)||'&nbsp;'}</p>${(original?e.trigger:confirmed('trigger'))?`<p><strong>Trigger:</strong> ${esc(original?e.trigger:confirmed('trigger'))}</p>`:''}${original&&e.sourceNotes?`<p class="notice">${esc(e.sourceNotes)}</p>`:''}${original?e.teams.map(teamTable).join('')+pokemonCards(e.giftPokemon,e.giftNote||'Gift Pokémon')+pokemonCards(e.featuredPokemon,'Also appears in this scene'):confirmedScene(c,e)}${mode==='drafts'?draftScene(c,e):''}</div></details>`;
}
function confirmedScene(c,e){const teams=Array.from({length:Math.max(1,e.teams.length)},(_,i)=>{const value=confirmedValue(c,'team',e.id,i);if(value===null)return `<div class="blank-team" aria-label="Unconfirmed team ${i+1}"></div>`;return value.length?teamTable({label:'Confirmed team '+(i+1),pokemon:value,confirmed:true}):'<p class="help">Confirmed: no Pokémon in this team.</p>';}).join('');return PUBLIC_SCENE_FIELDS.filter(k=>!['title','location','phase','summary','trigger','tags'].includes(k)).map(key=>readonlyField(SCENE_LABELS[key],confirmedValue(c,'scene',e.id,key),confirmedEntry(c,'scene',e.id,key))).join('')+teams;}
function draftScene(c,e){const r=sceneRecord(c,e);return `<section class="scene-draft"><h3>Draft this appearance</h3><div class="actions"><button class="secondary" data-action="copy-scene" data-scene-id="${esc(e.id)}">Start from official appearance</button></div><div class="form-grid">${PUBLIC_SCENE_FIELDS.map(key=>`<div>${field(SCENE_LABELS[key],r[key],`data-scene="${esc(e.id)}" data-scene-field="${key}"`,['summary','dialogue','gifts','notes'].includes(key)?'textarea':'input')}${confirmControl(c,'scene',key,e.id)}</div>`).join('')}${field('DSPRE location / IDs (private)',r.where,`data-scene="${esc(e.id)}" data-scene-field="where"`)}${field('Test results (private)',r.testing,`data-scene="${esc(e.id)}" data-scene-field="testing"`,'textarea')}<label class="field"><span>Draft edit status</span><select data-scene="${esc(e.id)}" data-scene-field="status">${STATUSES.map(s=>`<option value="${s}" ${r.status===s?'selected':''}>${STATUS_LABEL[s]}</option>`).join('')}</select></label></div><h3>Draft Pokémon teams</h3>${(e.teams.length?e.teams:[{label:'Custom team / gift Pokémon'}]).map((t,index)=>teamEditor(c,e,index,t)+confirmControl(c,'team',index,e.id)).join('')}</section>`;}
function teamTable(t){return `<p class="team-label">${esc(t.label||'Original Platinum team')}</p>${t.notes?`<p class="help">${esc(t.notes)}</p>`:''}<div class="table-wrap"><table class="illustrated-team"><thead><tr><th>Pokémon</th><th>Level</th><th>Ability</th><th>Held item</th><th>Moves</th></tr></thead><tbody>${t.pokemon.map(p=>`<tr><td><div class="team-species">${pokemonImage(p.species)}<strong>${esc(p.species)}</strong></div></td><td class="level">${esc(p.level??p.levelNote??'Not listed')}</td><td>${esc(p.ability||(!t.confirmed?'Not verified':''))}</td><td>${esc(p.item??(!t.confirmed?'Not verified':''))}</td><td>${esc(arr(p.moves).join(' · ')||(!t.confirmed?'Not verified':''))}</td></tr>`).join('')}</tbody></table></div>`;}
function filterTimeline(){const value=$('phase-filter')?.value||'';document.querySelectorAll('.encounter').forEach(el=>{const m=el.dataset.marker||'';el.hidden=value==='battle'?!m.includes('battle'):value==='reward'?!/gift|item/.test(m):value==='progress'?!m.includes('progress'):value==='repeat'?!m.includes('repeat'):value==='post'?!m.includes('postgame'):value==='optional'?!m.includes('optional'):false;});}
function draftValue(c,scope,eid,key){if(scope==='profile')return record(c).profile[key];if(scope==='image')return record(c).image;const e=c.encounters.find(e=>e.id===eid);if(!e)return null;if(scope==='scene')return sceneRecord(c,e)[key];return customTeam(c,e,key);}
function confirmValue(c,scope,eid,key,withdraw=false){
 if(mode!=='drafts'||!['profile','image','scene','team'].includes(scope))return false;
 if(scope==='image'&&!withdraw&&!isImage(record(c).image)){toast('Add a draft image before confirming it, or withdraw the existing confirmation.');return false;}
 if(scope==='profile'&&!PROFILE_FIELDS.includes(key)||scope==='scene'&&!PUBLIC_SCENE_FIELDS.includes(key))return false;
 const known=c.encounters.find(e=>e.id===eid);if(['scene','team'].includes(scope)&&!known)return false;
 if(scope==='team'&&(!Number.isInteger(Number(key))||Number(key)<0||Number(key)>=Math.max(1,known.teams.length)))return false;
 const now=new Date().toISOString(),previous=confirmedEntry(c,scope,eid,key),value=withdraw?null:copy(draftValue(c,scope,eid,key));
 const entry={value,confirmedAt:now,romVersion:str(notebook.project.romVersion,200)};
 const [obj,k]=snapshotSlot(notebook.confirmed,c.id,scope,eid,key,true);obj[k]=entry;notebook.confirmed.updatedAt=now;
 notebook.history.push({cid:c.id,scope,eid,key:String(key),date:now,previous:previous?copy(previous):null,next:copy(entry)});notebook.history=notebook.history.slice(-200);
 save();toast(withdraw?'Confirmation withdrawn. The draft is unchanged.':'Confirmed copy saved for Luce’s Version.');return true;
}
function publicationPanel(){if(mode!=='drafts')return '';const entries=allEntries(mergedSnapshot()).filter(x=>x[4].value!==null),local=allEntries(notebook.confirmed).filter(([cid,scope,eid,key,entry])=>JSON.stringify(entry)!==JSON.stringify(entryIn(published,cid,scope,eid,key))).length;return `<section class="panel publication-panel"><h2>Backups & confirmed snapshot</h2><p>Complete backups include private drafts, confirmations, images and confirmation history. The separate confirmed snapshot contains only explicitly confirmed values.</p><div class="actions"><button class="primary" data-action="export">Export complete backup</button><button data-action="import">Import backup</button><button data-action="csv">Export draft change log</button></div><h3>Share Luce’s Version across devices</h3><p>${entries.length} confirmed fields / teams · ${local} local confirmations or withdrawals awaiting publication.</p>${snapshotError?`<p class="notice">${esc(snapshotError)}</p>`:''}<ol class="publish-steps"><li>Export the confirmed snapshot as <strong>confirmed.json</strong>.</li><li>Upload it to the repository’s <strong>characters</strong> folder, replacing the existing file, and commit to main.</li><li>GitHub Pages loads the shared snapshot on each device after deployment.</li></ol><div class="actions"><button data-action="export-confirmed">Export confirmed snapshot</button><a class="button-link" href="https://github.com/Kemsypt/luce-pokedex/upload/main/characters" target="_blank" rel="noopener">Open GitHub uploader ↗</a></div><p class="help">You can also provide the exported confirmed.json here and ask for it to be published. Draft notes, testing details and unchecked changes are excluded from that file. Confirming a value saves it locally; uploading the snapshot publishes it.</p></section>`;}
function historyPanel(){const rows=notebook.history.slice(-12).reverse();return rows.length?`<section class="panel"><h2>Confirmation history</h2><p class="help">Earlier confirmed copies are retained in the complete backup. Latest changes:</p>${rows.map(x=>`<div class="recent-item"><span>${esc(DATA.find(c=>c.id===x.cid)?.name||x.cid)}</span><span>${esc(x.scope+' / '+x.key)} · ${x.next.value===null?'withdrawn':'confirmed'}</span><small>${esc(x.date.slice(0,10))}</small></div>`).join('')}</section>`:'';}
function bindCommon(c){
 document.querySelectorAll('img[data-art-fallback]').forEach(img=>img.onerror=()=>{if(img.dataset.artFallback){img.src=img.dataset.artFallback;delete img.dataset.artFallback;img.classList.add('pixel');}else img.hidden=true;});
 if($('phase-filter'))$('phase-filter').onchange=filterTimeline;
 if(mode!=='drafts')return;
 document.querySelectorAll('[data-project]').forEach(el=>el.oninput=()=>{notebook.project[el.dataset.project]=el.value;save();});
 document.querySelectorAll('[data-profile]').forEach(el=>el.oninput=()=>{record(c).profile[el.dataset.profile]=el.value;save();if(el.dataset.profile==='newName')buildNav();});
 document.querySelectorAll('[data-linked]').forEach(el=>el.onchange=()=>{record(c).linked[el.dataset.linked]=el.checked;save();});
 document.querySelectorAll('[data-change]').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{const x=record(c).changes.find(x=>x.id===el.dataset.change);x[el.dataset.changeField]=el.value;updateDate(x);if(el.dataset.changeField==='status'){if(['edited','tested'].includes(x.status)&&!x.date)x.date=new Date().toISOString().slice(0,10);save();view();}else save();}));
 document.querySelectorAll('[data-scene-field]').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{const e=c.encounters.find(e=>e.id===el.dataset.scene),r=sceneRecord(c,e);r[el.dataset.sceneField]=el.value;updateDate(r);save();}));
 document.querySelectorAll('[data-team-edit]').forEach(el=>el.oninput=()=>{const e=c.encounters.find(e=>e.id===el.dataset.teamEdit),p=sceneRecord(c,e).teams[el.dataset.team][Number(el.dataset.pokemon)],key=el.dataset.pokemonField;p[key]=key==='moves'?el.value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,4):key==='level'?(el.value===''?'':Math.min(100,Math.max(1,Number(el.value)))):el.value;updateDate(sceneRecord(c,e));save();});
 document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el,c));
 if($('custom-image'))$('custom-image').onchange=e=>uploadImage(e.target.files[0],c);
}
function refreshTeam(c,e,index){refreshPreservingScenes();}
function refreshPreservingScenes(){const ids=[...document.querySelectorAll('.encounter[open]')].map(el=>el.dataset.encounter),filter=$('phase-filter')?.value||'',scroll=window.scrollY;view();for(const id of ids){const el=document.querySelector(`[data-encounter="${CSS.escape(id)}"]`);if(el)el.open=true;}if($('phase-filter')){$('phase-filter').value=filter;filterTimeline();}window.scrollTo({top:scroll,behavior:'instant'});}
function action(el,c){
 if(mode!=='drafts')return;
 const a=el.dataset.action;
 if(a==='export')return exportBackup();if(a==='csv')return exportCSV();if(a==='export-confirmed')return exportConfirmed();if(a==='import')return $('import-file').click();
 if(a==='confirm-value'||a==='unconfirm-value'){if(confirmValue(c,el.dataset.confirmScope,el.dataset.confirmScene,el.dataset.confirmKey,a==='unconfirm-value'))refreshPreservingScenes();return;}
 if(a==='copy-profile'){if(PROFILE_FIELDS.some(k=>record(c).profile[k])&&!confirm('Replace draft profile fields with the original profile? Confirmed values are retained.'))return;record(c).profile={newName:c.name,personality:c.personality,relationship:arr(c.relationships).join('\n'),role:c.role,appearance:'',notes:''};save();view();return;}
 if(a==='copy-scene'){const e=c.encounters.find(e=>e.id===el.dataset.sceneId),r=sceneRecord(c,e);if(['title','location','summary','tags'].some(k=>r[k])&&!confirm('Replace these draft appearance fields with the original reference? Confirmed values are retained.'))return;for(const key of ['title','location','phase','summary','trigger'])r[key]=e[key]||'';r.tags=arr(e.tags).join(', ');save();refreshPreservingScenes();return;}
 if(a==='remove-image'){record(c).image='';save();view();return;}
 if(a==='add-change'){record(c).changes.push({id:crypto.randomUUID(),title:'New change',category:'Other',original:'',planned:'',actual:'',where:'',testing:'',romVersion:notebook.project.romVersion,date:'',status:'planned',updatedAt:new Date().toISOString()});save();view();document.querySelector('.change-item:last-child input')?.focus();return;}
 if(a==='remove-change'){if(!confirm('Delete this draft change record?'))return;record(c).changes=record(c).changes.filter(x=>x.id!==el.dataset.changeId);save();view();return;}
 if(['copy-team','add-pokemon','remove-pokemon'].includes(a)){const e=c.encounters.find(e=>e.id===el.dataset.sceneId),index=Number(el.dataset.team),r=sceneRecord(c,e);if(!r.teams[index])r.teams[index]=[];if(a==='copy-team'){if(r.teams[index].length&&!confirm('Replace this draft team with the original team? The confirmed copy is retained.'))return;r.teams[index]=cleanParty(e.teams[index].pokemon);}if(a==='add-pokemon'&&r.teams[index].length<6)r.teams[index].push({species:'',level:'',ability:'',item:'',moves:[]});if(a==='remove-pokemon')r.teams[index].splice(Number(el.dataset.pokemon),1);updateDate(r);save();refreshTeam(c,e,index);}
}
function save(force=false){if(mode!=='drafts'&&!force)return;notebook.updatedAt=new Date().toISOString();$('save-status').textContent='Saving…';const snapshot=copy(notebook);saveChain=saveChain.catch(()=>{}).then(async()=>{try{if(db)await persistDB(snapshot);else localStorage.setItem(KEY,JSON.stringify(snapshot));$('save-status').textContent='Drafts saved on this browser';$('save-status').classList.remove('error');}catch(error){$('save-status').textContent='Save failed — export a backup';$('save-status').classList.add('error');toast('Browser storage is unavailable or full. Export a complete backup to keep your work.');throw error;}});saveChain.catch(()=>{});}
function sanitiseSnapshot(raw){
 if(!raw||raw.schema!==1||raw.kind!=='luce-confirmed'||!raw.characters||typeof raw.characters!=='object'||Array.isArray(raw.characters))throw Error('Invalid confirmed snapshot.');
 const result=EMPTY_SNAPSHOT();result.updatedAt=iso(raw.updatedAt);
 for(const c of DATA){const x=raw.characters[c.id];if(!x||typeof x!=='object')continue;const add=(scope,eid,key,input)=>{if(!input||!iso(input.confirmedAt)||!Object.hasOwn(input,'value'))return;let value=input.value;if(value!==null){if(scope==='team'){if(!Array.isArray(value))return;value=cleanParty(value);}else if(scope==='image'){if(!isImage(value))return;}else{if(typeof value!=='string')return;value=str(value);}}const [obj,k]=snapshotSlot(result,c.id,scope,eid,key,true);obj[k]={value,confirmedAt:iso(input.confirmedAt),romVersion:str(input.romVersion,200)};};
  for(const key of PROFILE_FIELDS)add('profile','',key,x.profile?.[key]);add('image','','',x.image);
  for(const e of c.encounters){const r=x.encounters?.[e.id];if(!r)continue;for(const key of PUBLIC_SCENE_FIELDS)add('scene',e.id,key,r.fields?.[key]);for(let i=0;i<Math.max(1,e.teams.length);i++)add('team',e.id,i,r.teams?.[i]);}
 }
 return result;
}
function sanitiseImport(raw){
 if(!raw||![1,2].includes(raw.schema))throw Error('This is not a supported Luce character notebook.');
 const legacy=sanitiseLegacy({...raw,schema:1});
 const result={...legacy,schema:2,confirmed:raw.schema===2?sanitiseSnapshot(raw.confirmed||EMPTY_SNAPSHOT()):EMPTY_SNAPSHOT(),history:[]};
 for(const c of DATA){const original=raw.characters?.[c.id],r=result.characters[c.id];if(!r)continue;for(const e of c.encounters){const prior=original?.encounters?.[e.id],current=r.encounters[e.id];if(!current)continue;for(const key of SCENE_FIELDS)if(!['status','testing','where','notes','gifts','dialogue'].includes(key))current[key]=str(prior?.[key]);}}
 if(raw.schema===2)for(const x of arr(raw.history).slice(-200)){const c=DATA.find(c=>c.id===x.cid);if(!c||!iso(x.date)||!['profile','image','scene','team'].includes(x.scope))continue;const one=EMPTY_SNAPSHOT(),[obj,k]=snapshotSlot(one,c.id,x.scope,str(x.eid,100),str(x.key,100),true);obj[k]=x.next;const clean=entryIn(sanitiseSnapshot(one),c.id,x.scope,str(x.eid,100),str(x.key,100));if(!clean)continue;let previous=null;if(x.previous){obj[k]=x.previous;previous=entryIn(sanitiseSnapshot(one),c.id,x.scope,str(x.eid,100),str(x.key,100));}result.history.push({cid:c.id,scope:x.scope,eid:str(x.eid,100),key:str(x.key,100),date:iso(x.date),previous,next:clean});}
 return result;
}
function backupPayload(){return {...copy(notebook),confirmed:mergedSnapshot()};}
function exportBackup(){if(mode!=='drafts')return;download(JSON.stringify(backupPayload(),null,2),'luce-character-notebook-'+new Date().toISOString().slice(0,10)+'.json','application/json');toast('Complete backup exported: drafts, confirmations, images and history.');}
function exportConfirmed(){if(mode!=='drafts')return;download(JSON.stringify(mergedSnapshot(),null,2),'confirmed.json','application/json');toast('Confirmed snapshot exported. Upload confirmed.json to GitHub to share it.');}
async function chooseImport(file){if(mode!=='drafts'||!file)return;if(file.size>160*1024*1024){toast('Backup is too large (maximum 160 MB).');return;}try{pendingImport=sanitiseImport(JSON.parse(await file.text()));$('import-summary').textContent=`This backup contains ${Object.keys(pendingImport.characters).length} draft records${file?' and '+allEntries(pendingImport.confirmed).length+' confirmation records':''}.`;$('import-dialog').showModal();}catch(error){toast('Could not import: '+error.message);}finally{$('import-file').value='';}}
async function loadPublished(){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch('confirmed.json',{cache:'no-cache',signal:controller.signal});if(!response.ok)throw Error('Snapshot unavailable');published=sanitiseSnapshot(await response.json());}catch{snapshotError='The shared snapshot could not be loaded. Local confirmations remain available. Refresh online to load the published version.';}finally{clearTimeout(timer);}}
async function init(){
 if(!DATA.length){$('main').innerHTML='<div class="notice">Character reference could not load. Refresh this page.</div>';return;}
 try{const stored=localStorage.getItem(KEY+'-mode');if(MODES.includes(stored))mode=stored;}catch{}
 let saved;
 try{db=await openDB();saved=await dbRequest(db.transaction('notebook').objectStore('notebook').get('current'));}catch{db=null;try{saved=JSON.parse(localStorage.getItem(KEY)||'null');}catch{}}
 if(!saved)try{saved=JSON.parse(localStorage.getItem(KEY)||'null');}catch{}
 if(saved)try{notebook=sanitiseImport(saved);if(saved.schema===1){if(db){const tx=db.transaction('notebook','readwrite');tx.objectStore('notebook').put(saved,'pre-v2');}else try{localStorage.setItem(KEY+'-pre-v2',JSON.stringify(saved));}catch{}save(true);}}catch{try{if(db){const recovery=db.transaction('notebook','readwrite');recovery.objectStore('notebook').put(saved,'recovery-unreadable');}else localStorage.setItem(KEY+'-recovery-unreadable',JSON.stringify(saved));}catch{}toast('Saved notebook could not be read. A recovery copy was retained; import a backup to recover it.');}
 DATA.forEach(record);$('group').innerHTML='<option value="">All characters</option>'+[...new Set(DATA.map(c=>c.category))].map(g=>`<option>${esc(g)}</option>`).join('');
 $('search').oninput=()=>{if(location.hash&&window.matchMedia('(max-width:760px)').matches)location.hash='';else if(!location.hash)view();else buildNav();};$('group').onchange=()=>{if(location.hash)location.hash='';else view();};
 $('export').onclick=exportBackup;$('import').onclick=()=>{if(mode==='drafts')$('import-file').click();};$('import-file').onchange=e=>chooseImport(e.target.files[0]);
 $('import-cancel').onclick=()=>{pendingImport=null;$('import-dialog').close();};$('import-confirm').onclick=()=>{if(mode!=='drafts'||!pendingImport)return;notebook=pendingImport;pendingImport=null;DATA.forEach(record);save();$('import-dialog').close();view();toast('Complete notebook restored.');};
 document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>switchMode(button.dataset.mode));
 window.addEventListener('hashchange',()=>{activeTab='overview';draftReturnTab=null;view();$('main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});});
 view();await loadPublished();if(mode==='luce')refreshPreservingScenes();$('save-status').textContent=saved?'Existing work loaded into Drafts':'Drafts save on this browser';
}

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=u=>{try{const url=new URL(u,location.href);return ['https:','http:'].includes(url.protocol)?url.href:'#';}catch{return '#';}};
const arr=v=>Array.isArray(v)?v:typeof v==='string'?[v]:[];
function defaultChanges(c){return [ ['identity','Name and identity','Name',c.name],['dialogue','Dialogue and name references','Dialogue','Original Platinum dialogue'],['overworld','Overworld sprites','Sprite','Original overworld graphics'],['battle','Battle portrait / artwork','Sprite','Original trainer graphics'],['teams','Pokémon teams and gifts','Team','Original teams and gifts'],['events','Event and relationship checks','Event','Original event scripts'],['test','Playtest all appearances','Testing','Original encounter progression'] ].map(([id,title,category,original])=>({id,title,category,original,planned:'',actual:'',where:'',testing:'',romVersion:'',date:'',status:'planned',updatedAt:null}));}
function field(label,value,attrs='',type='input'){return `<label class="field"><span>${esc(label)}</span>${type==='textarea'?`<textarea ${attrs}>${esc(value)}</textarea>`:`<input ${attrs} value="${esc(value)}">`}</label>`;}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4500);}
function dbRequest(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open(KEY,1);request.onupgradeneeded=()=>request.result.createObjectStore('notebook');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
function persistDB(value){return new Promise((resolve,reject)=>{const tx=db.transaction('notebook','readwrite');tx.objectStore('notebook').put(value,'current');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function list(title,values){const items=arr(values);return items.length?`<h3>${esc(title)}</h3><ul>${items.map(v=>`<li>${esc(typeof v==='object'?v.description||JSON.stringify(v):v)}</li>`).join('')}</ul>`:'';}
function gallery(c){return arr(c.images).length?`<div class="gallery">${c.images.map(i=>`<figure><img class="${/sprite/i.test(i.label)?'pixel':''}" src="${esc(i.path?'images/'+i.path:i.url||'')}" alt="${esc(i.label+' — '+c.name)}" loading="lazy"><figcaption>${esc(i.label)}</figcaption></figure>`).join('')}</div>`:'';}
function sources(c){const refs=[...arr(c.sources),{url:'https://github.com/PokeAPI/sprites',title:'Official Pokémon artwork and Platinum sprite archive'},...arr(c.images).filter(i=>i.source).map(i=>({url:i.source,title:i.label+' — image source'}))];return `<section class="panel"><h2>Sources & reference coverage</h2><p>${esc(c.sourceNotes||'This profile summarises documented Platinum events. A continuous conversation counts as one scene. Optional and repeatable events have separate labels; trigger requirements are linked to the reference sources.')}</p><ul class="source-list">${refs.map(s=>{const u=typeof s==='string'?s:s.url;return `<li><a href="${esc(safeURL(u))}" target="_blank" rel="noopener">${esc(typeof s==='object'?s.title||u:u)}</a></li>`;}).join('')}</ul></section>`;}
function customTeam(c,e,index){return sceneRecord(c,e).teams[index]||[];}
function teamEditor(c,e,index,t){const team=customTeam(c,e,index);return `<div class="custom-team" data-team-scene="${esc(e.id)}" data-team-index="${index}"><p class="team-label">${esc(t.label||'Custom team')}</p><div class="actions">${arr(t.pokemon).length&&!t.pool?`<button data-action="copy-team" data-scene-id="${esc(e.id)}" data-team="${index}">Start from original team</button>`:''}<button data-action="add-pokemon" data-scene-id="${esc(e.id)}" data-team="${index}" ${team.length>=6?'disabled':''}>+ Pokémon</button></div><div class="team-editor-heading">Pokémon · level · ability · item · moves</div><div class="team-editor">${team.map((p,pi)=>`<div class="team-edit-row">${[['species','Pokémon','text'],['level','Level','number'],['ability','Ability','text'],['item','Held item','text'],['moves','Moves, separated by commas','text']].map(([k,l,type])=>`<input class="${k}" aria-label="${esc(l+' '+(pi+1)+' '+(t.label||'custom team'))}" type="${type}" ${k==='level'?'min="1" max="100"':''} placeholder="${esc(l)}" value="${esc(k==='moves'?arr(p[k]).join(', '):p[k])}" data-team-edit="${esc(e.id)}" data-team="${index}" data-pokemon="${pi}" data-pokemon-field="${k}">`).join('')}<button aria-label="Remove Pokémon ${pi+1}" data-action="remove-pokemon" data-scene-id="${esc(e.id)}" data-team="${index}" data-pokemon="${pi}">×</button></div>`).join('')}</div></div>`;}
function changes(c){const r=record(c),p=progress(c),sceneEdits=Object.values(r.encounters).filter(e=>e.status!=='planned'||e.notes||e.dialogue||e.gifts||Object.keys(e.teams).length).length;return `<div class="stats"><div class="stat"><b>${p.total}</b><span>Checklist items</span></div><div class="stat"><b>${p.edited}</b><span>Edited or tested</span></div><div class="stat"><b>${p.done}</b><span>Tested</span></div><div class="stat"><b>${sceneEdits}</b><span>Appearances customised</span></div></div><div class="section-title"><h2>Change log & testing checklist</h2><button class="primary" data-action="add-change">+ Add change</button></div><p class="help">Record what you plan, what you actually edited and where. “Edited” means the ROM is changed; “Tested” means you have checked the result in-game. Encounter statuses are tracked separately in Appearances & teams.</p>${r.changes.map(changeHTML).join('')}`;}
function changeHTML(x){return `<section class="change-item status-${x.status}" data-change-id="${esc(x.id)}"><div class="change-top"><label><span class="sr-only">Change title</span><input data-change="${esc(x.id)}" data-change-field="title" value="${esc(x.title)}"></label><label><span class="sr-only">Change status</span><select data-change="${esc(x.id)}" data-change-field="status">${STATUSES.map(s=>`<option value="${s}" ${x.status===s?'selected':''}>${STATUS_LABEL[s]}</option>`).join('')}</select></label></div><div class="form-grid">${changeField(x,'category','Category')}${changeField(x,'original','Original value / behaviour')}${changeField(x,'planned','Planned replacement',true)}${changeField(x,'actual','Actual change made',true)}${changeField(x,'where','Where edited — text / script / trainer IDs')}${changeField(x,'romVersion','ROM build / backup')}${changeField(x,'date','Edit date',false,'date')}${changeField(x,'testing','Test result / outstanding issues',true)}</div><div class="change-meta"><span>${x.updatedAt?'Updated '+esc(x.updatedAt.slice(0,10)):'Not updated yet'}</span><button class="danger" data-action="remove-change" data-change-id="${esc(x.id)}">Delete record</button></div></section>`;}
function changeField(x,k,label,multi=false,type='text'){return field(label,x[k],`data-change="${esc(x.id)}" data-change-field="${k}" ${!multi?'type="'+type+'"':''}`,multi?'textarea':'input');}
function recentHTML(){const entries=DATA.flatMap(c=>record(c).changes.filter(x=>x.updatedAt).map(x=>({c,x}))).sort((a,b)=>b.x.updatedAt.localeCompare(a.x.updatedAt)).slice(0,8);return entries.length?`<section class="panel"><h2>Recently updated changes</h2>${entries.map(({c,x})=>`<div class="recent-item"><a href="#${esc(c.id)}">${esc(record(c).profile.newName||c.name)}</a><span>${esc(x.title)} · ${STATUS_LABEL[x.status]}</span><small>${esc(x.updatedAt.slice(0,10))}</small></div>`).join('')}</section>`:'';}
function uploadImage(file,c){if(mode!=='drafts'||!file)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type)||file.size>8*1024*1024){toast('Choose a PNG, JPEG, WebP or GIF image under 8 MB.');return;}const reader=new FileReader();reader.onload=()=>{if(mode!=='drafts')return;record(c).image=reader.result;save();view();toast('Replacement image added. Export a backup to keep a copy.');};reader.onerror=()=>toast('Could not read that image.');reader.readAsDataURL(file);}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCSV(){if(mode!=='drafts')return;const headers=['Character','Replacement','Change','Category','Original','Planned','Actual','Where edited','Status','ROM build','Date','Testing'];const rows=[headers,...DATA.flatMap(c=>record(c).changes.map(x=>[c.name,record(c).profile.newName,x.title,x.category,x.original,x.planned,x.actual,x.where,STATUS_LABEL[x.status],x.romVersion,x.date,x.testing]))];const csv=rows.map(row=>row.map(x=>'"'+String(x??'').replace(/^\s*[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');download('\ufeff'+csv,'luce-character-change-log.csv','text/csv;charset=utf-8');}
function sanitiseLegacy(raw){if(!raw||raw.schema!==1||!raw.characters||typeof raw.characters!=='object'||Array.isArray(raw.characters))throw Error('This is not a version 1 Luce character notebook.');const str=(v,max=30000)=>typeof v==='string'?v.slice(0,max):'',out={schema:1,updatedAt:str(raw.updatedAt),project:{romVersion:str(raw.project?.romVersion),notes:str(raw.project?.notes)},characters:{}};for(const c of DATA){const x=raw.characters[c.id];if(!x)continue;if(typeof x!=='object')throw Error('Invalid character record.');const r={profile:{},image:'',changes:[],linked:{},encounters:{}};PROFILE_FIELDS.forEach(k=>r.profile[k]=str(x.profile?.[k]));if(typeof x.image==='string'&&/^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(x.image)&&x.image.length<=12*1024*1024)r.image=x.image;if(!Array.isArray(x.changes)||x.changes.length>500)throw Error('Invalid change list.');const ids=new Set();r.changes=x.changes.map((v,i)=>{const y={id:str(v.id,100)||crypto.randomUUID(),updatedAt:str(v.updatedAt,100)};if(ids.has(y.id))y.id=crypto.randomUUID();ids.add(y.id);CHANGE_FIELDS.forEach(k=>y[k]=str(v[k]));if(!STATUSES.includes(y.status))y.status='planned';return y;});arr(c.linkedChanges).forEach((v,i)=>r.linked[i]=x.linked?.[i]===true);arr(c.encounters).forEach(e=>{const z=x.encounters?.[e.id];if(!z)return;const scene={notes:str(z.notes),dialogue:str(z.dialogue),gifts:str(z.gifts),where:str(z.where),testing:str(z.testing),status:STATUSES.includes(z.status)?z.status:'planned',updatedAt:str(z.updatedAt,100),teams:{}};for(let i=0;i<Math.max(1,arr(e.teams).length);i++){if(!Array.isArray(z.teams?.[i]))continue;scene.teams[i]=z.teams[i].slice(0,6).map(p=>({species:str(p.species,200),level:p.level==null||p.level===''?'':Number.isFinite(Number(p.level))?Math.min(100,Math.max(1,Number(p.level))):'',ability:str(p.ability,200),item:str(p.item,200),moves:arr(p.moves).slice(0,4).map(x=>str(x,200))}));}r.encounters[e.id]=scene;});out.characters[c.id]=r;}return out;}
init();
